AWSTemplateFormatVersion: "2010-09-09"
Description: "Create outputs for default VPC and Subnets"

Parameters:
  CompanyName:
    Type: String
    Default: "My full company name"
  Company:
    Type: String
    Default: "comp"

Resources:
  NullResource:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  MyVPC:
    Description: Default VPC ID
    Value: "<Your Default VPC ID>"
    Export:
      Name: !Sub "${Company}-common-vpc"
  MySubnetA:
    Description: Default Subnet A ID
    Value: "<Your Default Subnet A ID>"
    Export:
      Name: !Sub "${Company}-common-subnet-a"
  MySubnetB:
    Description: Default Subnet B ID
    Value: "<Your Default Subnet B ID>"
    Export:
      Name: !Sub "${Company}-common-subnet-b"
  MySubnetC:
    Description: Default Subnet C ID
    Value: "<Your Default Subnet C ID>"
    Export:
      Name: !Sub "${Company}-common-subnet-c"
