AWSTemplateFormatVersion: "2010-09-09"
Description: "Create outputs for default VPC and Subnets for thePITman Solutions, LLC"

Parameters:
  CompanyName:
    Type: String
    Default: "thePITman Solutions LLC"
  Company:
    Type: String
    Default: "tpms"

Resources:
  NullResource:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  MyVPC:
    Description: Default VPC ID
    Value: "vpc-01b445c87e0974985"
    Export:
      Name: !Sub "${Company}-common-vpc"
  MySubnetA:
    Description: Default Subnet A ID
    Value: "subnet-00fb554a9e87fa1f5"
    Export:
      Name: !Sub "${Company}-common-subnet-a"
  MySubnetB:
    Description: Default Subnet B ID
    Value: "subnet-0aac249caf69af7a7"
    Export:
      Name: !Sub "${Company}-common-subnet-b"
  MySubnetC:
    Description: Default Subnet C ID
    Value: "subnet-0e5d3589b1839fca3"
    Export:
      Name: !Sub "${Company}-common-subnet-c"
